#pragma once
// Generated by Nulvex GMod Dumper
// 2026-10-05 09:33:09

// Interface pointers are process snapshots; rebase the emitted RVAs on restart.

#include <cstdint>

namespace nulvex::interfaces {

namespace client_dll {
    constexpr uint32_t VCLIENTTOOLS001 = 0x6C479764;
    constexpr uint32_t rva_VCLIENTTOOLS001 = 0x6D9764;
    // Shield_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t GameMovement001 = 0x6C5959F0;
    constexpr uint32_t rva_GameMovement001 = 0x7F59F0;
    // VortEmissive_IMaterialProxy003 = NULL (not instantiated)
    // HeliBlade_IMaterialProxy003 = NULL (not instantiated)
    // WorldDims_IMaterialProxy003 = NULL (not instantiated)
    // WaterLOD_IMaterialProxy003 = NULL (not instantiated)
    // MotionBlur_IMaterialProxy003 = NULL (not instantiated)
    // engine_post_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t VCENTERPRINT002 = 0x6C471E2C;
    constexpr uint32_t rva_VCENTERPRINT002 = 0x6D1E2C;
    // ToggleTexture_IMaterialProxy003 = NULL (not instantiated)
    // CurrentTime_IMaterialProxy003 = NULL (not instantiated)
    // TextureScroll_IMaterialProxy003 = NULL (not instantiated)
    // Pupil_IMaterialProxy003 = NULL (not instantiated)
    // PlayerLogo_IMaterialProxy003 = NULL (not instantiated)
    // EntityRandom_IMaterialProxy003 = NULL (not instantiated)
    // EntitySpeed_IMaterialProxy003 = NULL (not instantiated)
    // PlayerPosition_IMaterialProxy003 = NULL (not instantiated)
    // PlayerSpeed_IMaterialProxy003 = NULL (not instantiated)
    // PlayerView_IMaterialProxy003 = NULL (not instantiated)
    // PlayerTeamMatch_IMaterialProxy003 = NULL (not instantiated)
    // PlayerProximity_IMaterialProxy003 = NULL (not instantiated)
    // Health_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t VParticleSystemQuery001 = 0x6C46CB20;
    constexpr uint32_t rva_VParticleSystemQuery001 = 0x6CCB20;
    // ParticleSphereProxy_IMaterialProxy003 = NULL (not instantiated)
    // MatrixRotate_IMaterialProxy003 = NULL (not instantiated)
    // TextureTransform_IMaterialProxy003 = NULL (not instantiated)
    // SelectFirstIfNonZero_IMaterialProxy003 = NULL (not instantiated)
    // WrapMinMax_IMaterialProxy003 = NULL (not instantiated)
    // LessOrEqual_IMaterialProxy003 = NULL (not instantiated)
    // Empty_IMaterialProxy003 = NULL (not instantiated)
    // Abs_IMaterialProxy003 = NULL (not instantiated)
    // Exponential_IMaterialProxy003 = NULL (not instantiated)
    // GaussianNoise_IMaterialProxy003 = NULL (not instantiated)
    // UniformNoise_IMaterialProxy003 = NULL (not instantiated)
    // LinearRamp_IMaterialProxy003 = NULL (not instantiated)
    // Int_IMaterialProxy003 = NULL (not instantiated)
    // Frac_IMaterialProxy003 = NULL (not instantiated)
    // Equals_IMaterialProxy003 = NULL (not instantiated)
    // Sine_IMaterialProxy003 = NULL (not instantiated)
    // Clamp_IMaterialProxy003 = NULL (not instantiated)
    // Divide_IMaterialProxy003 = NULL (not instantiated)
    // Multiply_IMaterialProxy003 = NULL (not instantiated)
    // Subtract_IMaterialProxy003 = NULL (not instantiated)
    // Add_IMaterialProxy003 = NULL (not instantiated)
    // lamphalo_IMaterialProxy003 = NULL (not instantiated)
    // lampbeam_IMaterialProxy003 = NULL (not instantiated)
    // IsNPC_IMaterialProxy003 = NULL (not instantiated)
    // Ep1IntroVortRefract_IMaterialProxy003 = NULL (not instantiated)
    // EntityOriginAlyx_IMaterialProxy003 = NULL (not instantiated)
    // EntityOrigin_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t IEffects001 = 0x6C46C1A0;
    constexpr uint32_t rva_IEffects001 = 0x6CC1A0;
    // Dummy_IMaterialProxy003 = NULL (not instantiated)
    // ShadowModel_IMaterialProxy003 = NULL (not instantiated)
    // Shadow_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t ClientLeafSystem002 = 0x6C57ECB0;
    constexpr uint32_t rva_ClientLeafSystem002 = 0x7DECB0;
    constexpr uint32_t VClientEntityList003 = 0x6C55EB3C;
    constexpr uint32_t rva_VClientEntityList003 = 0x7BEB3C;
    constexpr uint32_t VClient017 = 0x6C469108;
    constexpr uint32_t rva_VClient017 = 0x6C9108;
    constexpr uint32_t VClientDllSharedAppSystems001 = 0x6C4690D0;
    constexpr uint32_t rva_VClientDllSharedAppSystems001 = 0x6C90D0;
    constexpr uint32_t GameClientExports001 = 0x6C4690CC;
    constexpr uint32_t rva_GameClientExports001 = 0x6C90CC;
    // Camo_IMaterialProxy003 = NULL (not instantiated)
    // MaterialModifyAnimated_IMaterialProxy003 = NULL (not instantiated)
    // MaterialModify_IMaterialProxy003 = NULL (not instantiated)
    // ConveyorScroll_IMaterialProxy003 = NULL (not instantiated)
    // BreakableSurface_IMaterialProxy003 = NULL (not instantiated)
    // AnimateSpecificTexture_IMaterialProxy003 = NULL (not instantiated)
    // AnimatedTexture_IMaterialProxy003 = NULL (not instantiated)
    // AnimatedOffsetTexture_IMaterialProxy003 = NULL (not instantiated)
    // AnimatedEntityTexture_IMaterialProxy003 = NULL (not instantiated)
    // Alpha_IMaterialProxy003 = NULL (not instantiated)
    // IntroScreen004 = NULL (not instantiated)
    // FleshInterior_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t VClientPrediction001 = 0x6C4BC0D8;
    constexpr uint32_t rva_VClientPrediction001 = 0x71C0D8;
    // YellowLevel_IMaterialProxy003 = NULL (not instantiated)
    // InvulnLevel_IMaterialProxy003 = NULL (not instantiated)
    // BurnLevel_IMaterialProxy003 = NULL (not instantiated)
    // spy_invis_IMaterialProxy003 = NULL (not instantiated)
    constexpr uint32_t ClientRenderTargets001 = 0x6C45B0C8;
    constexpr uint32_t rva_ClientRenderTargets001 = 0x6BB0C8;
    constexpr uint32_t IServerAddons001 = 0x6C45B058;
    constexpr uint32_t rva_IServerAddons001 = 0x6BB058;
}

namespace engine_dll {
    constexpr uint32_t VEngineVGui001 = 0x72D46288;
    constexpr uint32_t rva_VEngineVGui001 = 0x426288;
    constexpr uint32_t VSERVERENGINETOOLS001 = 0x72D4600C;
    constexpr uint32_t rva_VSERVERENGINETOOLS001 = 0x42600C;
    constexpr uint32_t VCLIENTENGINETOOLS001 = 0x72D46008;
    constexpr uint32_t rva_VCLIENTENGINETOOLS001 = 0x426008;
    constexpr uint32_t VTOOLFRAMEWORKVERSION002 = 0x72D45FC0;
    constexpr uint32_t rva_VTOOLFRAMEWORKVERSION002 = 0x425FC0;
    constexpr uint32_t VENGINETOOLFRAMEWORK003 = 0x72D45D88;
    constexpr uint32_t rva_VENGINETOOLFRAMEWORK003 = 0x425D88;
    constexpr uint32_t VENGINETOOL003 = 0x72D45D88;
    constexpr uint32_t rva_VENGINETOOL003 = 0x425D88;
    constexpr uint32_t XboxSystemInterface001 = 0x72D45D78;
    constexpr uint32_t rva_XboxSystemInterface001 = 0x425D78;
    constexpr uint32_t VProfExport001 = 0x72D45D50;
    constexpr uint32_t rva_VProfExport001 = 0x425D50;
    constexpr uint32_t VoiceServer002 = 0x72D45D48;
    constexpr uint32_t rva_VoiceServer002 = 0x425D48;
    constexpr uint32_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x72D45BB8;
    constexpr uint32_t rva_VENGINE_GAMEUIFUNCS_VERSION005 = 0x425BB8;
    constexpr uint32_t VENGINE_HLDS_API_VERSION002 = 0x72D45BF4;
    constexpr uint32_t rva_VENGINE_HLDS_API_VERSION002 = 0x425BF4;
    constexpr uint32_t VENGINE_LAUNCHER_API_VERSION004 = 0x72D45BC8;
    constexpr uint32_t rva_VENGINE_LAUNCHER_API_VERSION004 = 0x425BC8;
    constexpr uint32_t StaticPropMgrServer002 = 0x72D45B10;
    constexpr uint32_t rva_StaticPropMgrServer002 = 0x425B10;
    constexpr uint32_t StaticPropMgrClient004 = 0x72D45B0C;
    constexpr uint32_t rva_StaticPropMgrClient004 = 0x425B0C;
    constexpr uint32_t SpatialPartition001 = 0x73465618;
    constexpr uint32_t rva_SpatialPartition001 = 0xB45618;
    constexpr uint32_t VEngineRandom001 = 0x72D45AA0;
    constexpr uint32_t rva_VEngineRandom001 = 0x425AA0;
    constexpr uint32_t VEngineServerStringTable001 = 0x73464D64;
    constexpr uint32_t rva_VEngineServerStringTable001 = 0xB44D64;
    constexpr uint32_t VEngineClientStringTable001 = 0x73464D28;
    constexpr uint32_t rva_VEngineClientStringTable001 = 0xB44D28;
    constexpr uint32_t VModelInfoClient006 = 0x73463A98;
    constexpr uint32_t rva_VModelInfoClient006 = 0xB43A98;
    constexpr uint32_t VModelInfoServer004 = 0x73463B08;
    constexpr uint32_t rva_VModelInfoServer004 = 0xB43B08;
    constexpr uint32_t VModelInfoServer003 = 0x73463B08;
    constexpr uint32_t rva_VModelInfoServer003 = 0xB43B08;
    constexpr uint32_t GAMEEVENTSMANAGER001 = 0x72D44A54;
    constexpr uint32_t rva_GAMEEVENTSMANAGER001 = 0x424A54;
    constexpr uint32_t GAMEEVENTSMANAGER002 = 0x72D449B8;
    constexpr uint32_t rva_GAMEEVENTSMANAGER002 = 0x4249B8;
    constexpr uint32_t EngineTraceClient003 = 0x72D4499C;
    constexpr uint32_t rva_EngineTraceClient003 = 0x42499C;
    constexpr uint32_t EngineTraceServer003 = 0x72D44988;
    constexpr uint32_t rva_EngineTraceServer003 = 0x424988;
    constexpr uint32_t DownloadSystem001 = 0x72D44708;
    constexpr uint32_t rva_DownloadSystem001 = 0x424708;
    constexpr uint32_t VCvarQuery001 = 0x72D4411C;
    constexpr uint32_t rva_VCvarQuery001 = 0x42411C;
    constexpr uint32_t VEngineServer021 = 0x72D42DA4;
    constexpr uint32_t rva_VEngineServer021 = 0x422DA4;
    constexpr uint32_t GameServerData001 = 0x72D42C88;
    constexpr uint32_t rva_GameServerData001 = 0x422C88;
    constexpr uint32_t ISERVERPLUGINHELPERS001 = 0x72D42C00;
    constexpr uint32_t rva_ISERVERPLUGINHELPERS001 = 0x422C00;
    constexpr uint32_t VEngineRenderView014 = 0x72D32798;
    constexpr uint32_t rva_VEngineRenderView014 = 0x412798;
    constexpr uint32_t VEngineShadowMgr002 = 0x72FFE518;
    constexpr uint32_t rva_VEngineShadowMgr002 = 0x6DE518;
    constexpr uint32_t VEngineEffects001 = 0x72D325CC;
    constexpr uint32_t rva_VEngineEffects001 = 0x4125CC;
    constexpr uint32_t VEngineModel016 = 0x72D31A50;
    constexpr uint32_t rva_VEngineModel016 = 0x411A50;
    constexpr uint32_t VPhysicsDebugOverlay001 = 0x72D312FC;
    constexpr uint32_t rva_VPhysicsDebugOverlay001 = 0x4112FC;
    constexpr uint32_t VDebugOverlay003 = 0x72D312F8;
    constexpr uint32_t rva_VDebugOverlay003 = 0x4112F8;
    constexpr uint32_t VEngineClient013 = 0x72D071DC;
    constexpr uint32_t rva_VEngineClient013 = 0x3E71DC;
    constexpr uint32_t VEngineClient015 = 0x72D071DC;
    constexpr uint32_t rva_VEngineClient015 = 0x3E71DC;
    constexpr uint32_t IEngineSoundServer003 = 0x72D06004;
    constexpr uint32_t rva_IEngineSoundServer003 = 0x3E6004;
    constexpr uint32_t IEngineSoundClient003 = 0x72D06000;
    constexpr uint32_t rva_IEngineSoundClient003 = 0x3E6000;
}

namespace inputsystem_dll {
    constexpr uint32_t InputSystemVersion001 = 0x7290B000;
    constexpr uint32_t rva_InputSystemVersion001 = 0x2B000;
}

namespace lua_shared_dll {
    constexpr uint32_t LUASHARED003 = 0x6BD21610;
    constexpr uint32_t rva_LUASHARED003 = 0x81610;
    constexpr uint32_t LUACONVARS001 = 0x6BD21000;
    constexpr uint32_t rva_LUACONVARS001 = 0x81000;
}

namespace materialsystem_dll {
    // ShaderDLL004 = NULL (not instantiated)
    constexpr uint32_t ShaderSystem002 = 0x7089B3E4;
    constexpr uint32_t rva_ShaderSystem002 = 0x11B3E4;
    constexpr uint32_t VMaterialSystemStub001 = 0x7089B368;
    constexpr uint32_t rva_VMaterialSystemStub001 = 0x11B368;
    constexpr uint32_t VEngineCvar004 = 0x735DC800;
    constexpr uint32_t MaterialSystemHardwareConfig012 = 0x6FBEE008;
    constexpr uint32_t VMaterialSystemConfig002 = 0x7089B058;
    constexpr uint32_t rva_VMaterialSystemConfig002 = 0x11B058;
    constexpr uint32_t VMaterialSystem080 = 0x708A2878;
    constexpr uint32_t rva_VMaterialSystem080 = 0x122878;
    constexpr uint32_t COLORCORRECTION_VERSION_1 = 0x7089B004;
    constexpr uint32_t rva_COLORCORRECTION_VERSION_1 = 0x11B004;
}

namespace server_dll {
    constexpr uint32_t VSERVERCHOREOTOOLS001 = 0x5C52AD60;
    constexpr uint32_t rva_VSERVERCHOREOTOOLS001 = 0xA1AD60;
    constexpr uint32_t VSERVERTOOLS002 = 0x5C52AD5C;
    constexpr uint32_t rva_VSERVERTOOLS002 = 0xA1AD5C;
    constexpr uint32_t VSERVERTOOLS001 = 0x5C52AD5C;
    constexpr uint32_t rva_VSERVERTOOLS001 = 0xA1AD5C;
    constexpr uint32_t ServerGameTags001 = 0x5C524190;
    constexpr uint32_t rva_ServerGameTags001 = 0xA14190;
    constexpr uint32_t GameMovement001 = 0x5C60B080;
    constexpr uint32_t rva_GameMovement001 = 0xAFB080;
    constexpr uint32_t PluginHelpersCheck001 = 0x5C4DD4B0;
    constexpr uint32_t rva_PluginHelpersCheck001 = 0x9CD4B0;
    constexpr uint32_t BotManager001 = 0x5C4DC494;
    constexpr uint32_t rva_BotManager001 = 0x9CC494;
    constexpr uint32_t PlayerInfoManager002 = 0x5C4DC490;
    constexpr uint32_t rva_PlayerInfoManager002 = 0x9CC490;
    constexpr uint32_t PlayerInfoManager001 = 0x5C4DC498;
    constexpr uint32_t rva_PlayerInfoManager001 = 0x9CC498;
    constexpr uint32_t HLTVDirector001 = 0x5C4CC2BC;
    constexpr uint32_t rva_HLTVDirector001 = 0x9BC2BC;
    constexpr uint32_t VServerDllSharedAppSystems001 = 0x5C4CB6F4;
    constexpr uint32_t rva_VServerDllSharedAppSystems001 = 0x9BB6F4;
    constexpr uint32_t ServerGameClients004 = 0x5C4CB678;
    constexpr uint32_t rva_ServerGameClients004 = 0x9BB678;
    constexpr uint32_t ServerGameClients003 = 0x5C4CB678;
    constexpr uint32_t rva_ServerGameClients003 = 0x9BB678;
    constexpr uint32_t ServerGameEnts001 = 0x5C4CB6F0;
    constexpr uint32_t rva_ServerGameEnts001 = 0x9BB6F0;
    constexpr uint32_t ServerGameDLL009 = 0x5C4CB6E0;
    constexpr uint32_t rva_ServerGameDLL009 = 0x9BB6E0;
    constexpr uint32_t ServerGameDLL008 = 0x5C4CB6E0;
    constexpr uint32_t rva_ServerGameDLL008 = 0x9BB6E0;
    constexpr uint32_t IEffects001 = 0x5C4BA1BC;
    constexpr uint32_t rva_IEffects001 = 0x9AA1BC;
}

namespace studiorender_dll {
    constexpr uint32_t VStudioRender025 = 0x70701C30;
    constexpr uint32_t rva_VStudioRender025 = 0x7D1C30;
}

namespace vguimatsurface_dll {
    constexpr uint32_t VGUI_Surface030 = 0x6FDEA250;
    constexpr uint32_t rva_VGUI_Surface030 = 0x14A250;
}

namespace vphysics_dll {
    constexpr uint32_t VPhysicsSurfaceProps001 = 0x6FF09020;
    constexpr uint32_t rva_VPhysicsSurfaceProps001 = 0xD9020;
    constexpr uint32_t VPhysicsCollision007 = 0x6FF0808C;
    constexpr uint32_t rva_VPhysicsCollision007 = 0xD808C;
    constexpr uint32_t VPhysics031 = 0x6FF08020;
    constexpr uint32_t rva_VPhysics031 = 0xD8020;
}

namespace vstdlib_dll {
    constexpr uint32_t VProcessUtils001 = 0x735DB07C;
    constexpr uint32_t rva_VProcessUtils001 = 0x3B07C;
    constexpr uint32_t VEngineCvar004 = 0x735DC800;
    constexpr uint32_t rva_VEngineCvar004 = 0x3C800;
}

} // namespace nulvex::interfaces
