#pragma once
// Generated by Nulvex GMod Dumper
// 2026-10-05 09:33:09

// Absolute addresses are valid only for the sampled process; use RVAs after a restart.

#include <cstdint>

namespace nulvex::dump {

namespace client_dll {
    constexpr uint32_t dwBase = 0x6BDA0000; // constant | module base address
    constexpr uint32_t dwSize = 0x8D8000; // constant | module size
    constexpr uint32_t dwEntityList = 0x6C55EB3C; // exact_interface | VClientEntityList003 interface ptr
    constexpr uint32_t rvaEntityList = 0x7BEB3C;
    constexpr uint32_t dwClientDll = 0x6C469108; // exact_interface | VClient016 interface ptr
    constexpr uint32_t rvaClientDll = 0x6C9108;
    constexpr uint32_t dwGetAllClasses = 0x6BF73190; // runtime_validated | selected after full ClientClass traversal
    constexpr uint32_t rvaGetAllClasses = 0x1D3190;
    constexpr uint32_t nClient_GetAllClasses = 0x8; // runtime_validated | selected after full ClientClass traversal
    constexpr uint32_t dwClientClassHead = 0x6C51EB0C; // runtime_validated | ClientClass linked list
    constexpr uint32_t rvaClientClassHead = 0x77EB0C;
    constexpr int32_t  dwEntityArrayOffset = -262160; // runtime_validated | probe confirmed (internal disasm match)
    constexpr uint32_t nEntityStride = 0x10; // source_verified | CEntInfo: IHandleEntity*(+0) serial(+4) prev(+8) next(+C) = 16 bytes
    constexpr uint32_t nEntList_GetClientEntity = 0x3; // exact_interface | vtable index
    constexpr uint32_t nEntity_IClientNetworkable = 0x8; // source_verified | MSVC MI: IClientUnknown(+0) IClientRenderable(+4) IClientNetworkable(+8)
    constexpr uint32_t nNetworkable_GetClientClass = 0x2; // source_verified | IClientNetworkable vtbl: GetIClientUnknown(0) Release(1) GetClientClass(2)
    constexpr uint32_t kBaseShift = 0x4; // runtime_validated | probe validated (score=2160, teams=9, hp=9, origins=9, 214 entities)
}

namespace d3d9_dll {
    constexpr uint32_t dwBase = 0x6F980000; // constant | module base address
    constexpr uint32_t dwSize = 0x171000; // constant | module size
    constexpr uint32_t nReset = 0x10; // source_verified | IDirect3DDevice9::Reset vtable index
    constexpr uint32_t nPresent = 0x11; // source_verified | IDirect3DDevice9::Present vtable index
    constexpr uint32_t nEndScene = 0x2A; // source_verified | IDirect3DDevice9::EndScene vtable index
    constexpr uint32_t nDrawIndexedPrimitive = 0x52; // source_verified | IDirect3DDevice9 COM vtable index
}

namespace engine_dll {
    constexpr uint32_t dwBase = 0x72920000; // constant | module base address
    constexpr uint32_t dwSize = 0xBAC000; // constant | module size
    constexpr uint32_t ptrSignonState = 0x72E90360; // runtime_validated | VEngineClient IsInGame direct comparison
    constexpr uint32_t rva_ptrSignonState = 0x570360;
    constexpr uint32_t dwViewMatrix = 0x72D3189C; // runtime_validated | world-to-screen matrix (camera basis confirmed)
    constexpr uint32_t rvaViewMatrix = 0x41189C;
    constexpr uint32_t dwRenderEngine = 0x72D31800; // runtime_validated | render engine global ptr (matrix chain validated)
    constexpr uint32_t rvaRenderEngine = 0x411800;
    constexpr uint32_t nVtblWorldToScreen = 0x24; // exact_interface | vtbl[36] thunk -> render vtbl[13]
    constexpr uint32_t nVtblIsInGame = 0x1A; // exact_interface | VEngineClient vtable index
    constexpr uint32_t nVtblGetScreenSize = 0x5; // exact_interface
    constexpr uint32_t nVtblGetMaxClients = 0x2B; // exact_interface | returns ptr, not count
    constexpr uint32_t nGV_realtime = 0x0; // source_verified | CGlobalVarsBase::realtime (float)
    constexpr uint32_t nGV_framecount = 0x4; // source_verified | CGlobalVarsBase::framecount (int)
    constexpr uint32_t nGV_absoluteframetime = 0x8; // source_verified | CGlobalVarsBase::absoluteframetime (float)
    constexpr uint32_t nGV_curtime = 0xC; // source_verified | CGlobalVarsBase::curtime (float)
    constexpr uint32_t nGV_frametime = 0x10; // source_verified | CGlobalVarsBase::frametime (float)
    constexpr uint32_t nGV_maxClients = 0x14; // source_verified | CGlobalVarsBase::maxClients (int)
    constexpr uint32_t nGV_tickcount = 0x18; // source_verified | CGlobalVarsBase::tickcount (int)
    constexpr uint32_t nGV_interval_per_tick = 0x1C; // source_verified | CGlobalVarsBase::interval_per_tick (float)
    constexpr uint32_t nGV_interpolation_amount = 0x20; // source_verified | CGlobalVarsBase::interpolation_amount (float)
    constexpr uint32_t nGV_simTicksThisFrame = 0x24; // source_verified | CGlobalVarsBase::simTicksThisFrame (int)
    constexpr uint32_t nGV_network_protocol = 0x28; // source_verified | CGlobalVarsBase::network_protocol (int)
}

namespace gmod_exe {
    constexpr uint32_t dwBase = 0x470000; // constant | module base address
    constexpr uint32_t dwSize = 0xF1000; // constant | module size
}

namespace inputsystem_dll {
    constexpr uint32_t dwBase = 0x728E0000; // constant | module base address
    constexpr uint32_t dwSize = 0x34000; // constant | module size
}

namespace lua_shared_dll {
    constexpr uint32_t dwBase = 0x6BCA0000; // constant | module base address
    constexpr uint32_t dwSize = 0x90000; // constant | module size
}

namespace materialsystem_dll {
    constexpr uint32_t dwBase = 0x70780000; // constant | module base address
    constexpr uint32_t dwSize = 0x2153000; // constant | module size
}

namespace server_dll {
    constexpr uint32_t dwBase = 0x5BB10000; // constant | module base address
    constexpr uint32_t dwSize = 0xC44000; // constant | module size
}

namespace shaderapidx9_dll {
    constexpr uint32_t dwBase = 0x6FB00000; // constant | module base address
    constexpr uint32_t dwSize = 0x116000; // constant | module size
}

namespace studiorender_dll {
    constexpr uint32_t dwBase = 0x6FF30000; // constant | module base address
    constexpr uint32_t dwSize = 0x7E5000; // constant | module size
}

namespace tier0_dll {
    constexpr uint32_t dwBase = 0x73660000; // constant | module base address
    constexpr uint32_t dwSize = 0x50000; // constant | module size
}

namespace vguimatsurface_dll {
    constexpr uint32_t dwBase = 0x6FCA0000; // constant | module base address
    constexpr uint32_t dwSize = 0x189000; // constant | module size
}

namespace vphysics_dll {
    constexpr uint32_t dwBase = 0x6FE30000; // constant | module base address
    constexpr uint32_t dwSize = 0xF5000; // constant | module size
}

namespace vstdlib_dll {
    constexpr uint32_t dwBase = 0x735A0000; // constant | module base address
    constexpr uint32_t dwSize = 0xAA000; // constant | module size
}

namespace aob {

namespace client_dll {
    constexpr const char* aob_GetAllClasses = "A1 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC CC CC";
    constexpr const char* aob_GetClientEntity = "55 8B EC 8B 45 08 85 C0 78 1E 3D ?? ?? ?? ?? 7D 17 05 FF BF FF FF 03 C0 8B 0C C1 85 C9 74 09 8B 01 FF 50 18 5D C2 04 00 33 C0 5D C2 04 00 CC CC";
}

namespace engine_dll {
    constexpr const char* aob_IsInGame_vtbl26 = "83 3D ?? ?? ?? ?? 06 0F 94 C0 C3";
    constexpr const char* aob_GetLocalPlayer_fallback = "A1 ?? ?? ?? ?? 8B 40 0C C3";
    constexpr const char* aob_ViewMatrix_thunk = "8B 0D ?? ?? ?? ?? 8B 01 FF 60 34 CC CC CC";
    constexpr const char* aob_ViewMatrix_target = "83 B9 ?? ?? ?? ?? 01 7E 16 69 91 E0 00 00 00 8C";
}

} // namespace aob

} // namespace nulvex::dump
